### ISSUE TITLE
Calling resume session doesn't work

### ISSUE THREAD

**Issue by hipstersmoothie** [skyware-js/bot#16]
I used the session returned from login and it just fails with this error

![CleanShot 2024-11-11 at 01 20 21@2x](https://github.com/user-attachments/assets/efbcd6df-3533-4a35-b9d9-d72d03ee0cd1)

**Comment by futurGH** [comment]
Looks like a network error, is it happening consistently?

**Comment by hipstersmoothie** [comment]
yeah happen 100% of the time if I try to re-use a session

**Comment by StephanGeorg** [comment]
> I also see this happening. Not immediately, but after a few hours I get the error. And yes, in 100% of the time.
Just realized I was running it on a shared vCPU server which of course was the reason for this. 🙄

Amazing framework. Thank you so much.
