### ISSUE TITLE
Can't quote a post alongside with images unless the post is a Post object

### ISSUE THREAD

**Issue by aalku** [skyware-js/bot#18]
Hello. It's me again.

I'm saving some post references (uri+cid) in a database to quote them later and then I can't unless I use bot.getPosts() again to get Post objects. Is it really needed for them to be Post objects? I mean I will pass a reference { uri, cid } to a post, but not a Post object that you can check with "instanceof". I think as long as there's no images that check is not made. I undestand why it has to be a post but maybe not a "Post".

Thanks a lot.

https://github.com/skyware-js/bot/blob/5a495707d057002463be2c59bc7be6ca93e56437/src/bot/Bot.ts#L835

**Comment by futurGH** [comment]
Fair enough!

**Comment by aalku** [comment]
Your quick response is overwhelming. <3

**Comment by futurGH** [comment]
Fixed in 0.3.8!
