### ISSUE TITLE
BUG: Rate limit is 1000 times more limiting than intended

### ISSUE THREAD

**Issue by aalku** [skyware-js/bot#3]
Here you create the rate limiter with 3000 operations per 300*1000 seconds, so a thousand times less than the official rate.

https://github.com/skyware-js/bot/blob/7fa2b6eebbab85eb67afa2f5d51da71d8f54bb14/src/bot/Bot.ts#L139

As you can see it's supossed to be seconds and I guess you treat it as if it was milliseconds:
https://github.com/Borewit/rate-limit-threshold

So after some time your rate-limited client stops making my requests with sleeps, allowing me only 3000 calls per 3.5 days.

**Comment by futurGH** [comment]
Sorry, just noticed this! Good shout; I opened a PR in rate-limit-threshold and this will be fixed in 0.3.0.
