### ISSUE TITLE
Example on using session

### ISSUE THREAD

**Issue by dotslashf** [skyware-js/bot#4]
If the current session is expired,

how should i resume the session?
can you provide an example

**Comment by futurGH** [comment]
The session should automatically refresh the next time you make a call; if that isn't happening, can you provide a reproduction?

Resuming a session is only necessary if you saved the result of `Bot#login` and want to restart the bot without creating a new session.

**Comment by Cristuker** [comment]
Hi, I'm handling session this way now https://github.com/Cristuker/save-to-later/blob/main/src/config/agentProxy.ts
