### ISSUE TITLE
Cron Job

### ISSUE THREAD

**Issue by YuriGal** [skyware-js/bot#5]
Hi, I am not sure if I am doing something wrong, or it's a library issue. I have a very basic bot, that posts stuff on schedule:

```
const bot = new Bot();

await bot.login({
  identifier: process.env.BSKY_BOT_HANDLE!,
  password: process.env.BSKY_BOT_PASSWORD!,
});

const job = new CronJob('0 */2 * * *', async () => {
  await bot.post({
    text: "text of the post,
  });
});

job.start();
```

On the first run it posts the message successfully. But nothing is posted on the consecutive runs.  What am I missing? 

Thanks!

**Comment by futurGH** [comment]
Sorry, just noticed this! This shouldn't have anything to do with the library — if you can confirm that anything else (logging, etc) works fine in the cronjob and no errors are being thrown, I can check if something is going wrong and being silenced.

**Comment by YuriGal** [comment]
I think I might've figured it out. Session seems to be expiring (I think). I am checking if the bot has session, and if it doesn't - do a login again. Will test it to see if it fixes the issue.

**Comment by YuriGal** [comment]
Just checked the execution logs - nope that wasn't it. Inside of the cron job I both log the text of the message (via `console.log`) and post it via the bot. Message is logged successfully, but is not posted on consecutive job runs.

It _does_ work if I create a new bot instance on every job run

**Comment by futurGH** [comment]
Could the CronJob library you're using be silently catching an error? Can you wrap the `post` call in a try/catch and see if anything comes up?
